# Generated by Django 6.0.1 on 2026-03-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='experience',
            field=models.CharField(choices=[('beginner', 'Less than 6 months'), ('intermediate', '6 months to 2 years')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('c', 'C'), ('cpp', 'C++')], default='python', max_length=50),
        ),
    ]
