# Generated by Django 6.0.1 on 2026-03-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('language', models.CharField(choices=[('python', 'Python'), ('c', 'C'), ('cpp', 'C++')], default='python', max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('method', models.CharField(max_length=20)),
                ('concept_name', models.CharField(max_length=100)),
                ('explanation', models.TextField()),
                ('embedding', models.JSONField()),
                ('pattern_detected', models.BooleanField(default=False)),
                ('pattern_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
