# Generated by Django 6.0.1 on 2026-03-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buglog',
            old_name='text',
            new_name='error_message',
        ),
    ]
